# Netlify configuration for domain redirect
# Redirects all traffic from thomasjt.com to thomasthorstenson.com

[[redirects]]
  from = "https://thomasjt.com/*"
  to = "https://thomasthorstenson.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.thomasjt.com/*"
  to = "https://thomasthorstenson.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://thomasjt.netlify.app/*"
  to = "https://thomasthorstenson.com/:splat"
  status = 301
  force = true
