# Netlify configuration for domain redirect
# Redirects all traffic from www.thomasjt.com to www.thomasthorstenson.com

[[redirects]]
  from = "https://www.thomasjt.com/*"
  to = "https://www.thomasthorstenson.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.thomasjt.com/*"
  to = "https://www.thomasthorstenson.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://thomasjt.com/*"
  to = "https://www.thomasthorstenson.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://thomasjt.com/*"
  to = "https://www.thomasthorstenson.com/:splat"
  status = 301
  force = true
